mod helpers;
mod day01;
mod day02;
mod day03;
mod day04;
mod day05;
mod day06;
mod day07;
mod day08;
mod day09;
mod day10;
mod day11;
mod day12;
mod day13;
mod day14;

fn main() {
    day01::task1("".to_string());
    day01::task2("".to_string());
    day02::task1("".to_string());
    day02::task2("".to_string());
    day03::task1("".to_string());
    day03::task2("".to_string());
    day04::task1("".to_string());
    day04::task2("".to_string());
    day05::task1("".to_string());
    day05::task2("".to_string());
    day06::task1("".to_string());
    day06::task2("".to_string());
    day07::task1("".to_string());
    day07::task2("".to_string());
    day08::task1("".to_string());
    day08::task2("".to_string());
    day09::task1("".to_string());
    day09::task2("".to_string());
    day10::task1("".to_string());
    day10::task2("".to_string());
    day11::task1("".to_string());
    day11::task2("".to_string());
    day12::task1("".to_string());
    day12::task2("".to_string());
    day13::task1("".to_string());
    day13::task2("".to_string());
    day14::task1("".to_string());
    day14::task2("".to_string());
}